<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // A message from a teacher to every device in one classroom. Devices poll for
        // these (they never hold a socket), so an announcement stays fetchable until
        // expires_at, and a device that was offline when it was sent still gets it.
        Schema::create('announcements', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('classroom_id')->constrained()->cascadeOnDelete();
            $table->foreignId('sent_by')->constrained('users')->cascadeOnDelete();
            $table->string('message', 500);
            $table->timestamp('sent_at')->useCurrent();
            $table->timestamp('expires_at');
            $table->timestamps();

            $table->index(['classroom_id', 'id']);
        });

        // Delivery/read state, one row per device per announcement. Created when the
        // device first fetches it (delivered) and updated when the student dismisses
        // it (read). The teacher only ever sees counts and per-device state.
        Schema::create('announcement_receipts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('announcement_id')->constrained()->cascadeOnDelete();
            $table->foreignId('computer_id')->constrained()->cascadeOnDelete();
            $table->timestamp('delivered_at')->useCurrent();
            $table->timestamp('read_at')->nullable();

            $table->unique(['announcement_id', 'computer_id']);
        });

        // A student asking for the teacher's attention ("raise hand"). The uuid is
        // generated by the device so a retry after a dropped connection is idempotent.
        Schema::create('help_requests', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('classroom_id')->constrained()->cascadeOnDelete();
            $table->foreignId('computer_id')->constrained()->cascadeOnDelete();
            $table->foreignId('student_id')->nullable()->constrained()->nullOnDelete();
            $table->string('message', 200)->nullable();
            $table->enum('status', ['open', 'resolved', 'cancelled'])->default('open');
            $table->timestamp('requested_at')->useCurrent();
            $table->timestamp('resolved_at')->nullable();
            $table->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index(['classroom_id', 'status']);
            $table->index(['computer_id', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('help_requests');
        Schema::dropIfExists('announcement_receipts');
        Schema::dropIfExists('announcements');
    }
};
